In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [130]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [131]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [132]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [133]:
# Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [134]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [135]:
# extract year
date['date_year']=date['date'].dt.year

In [136]:
# extract month
date['date_month']=date['date'].dt.month

In [137]:
# extract date
date['date_month_name']=date['date'].dt.month_name

In [138]:
# extract day
date['date_day']=date['date'].dt.day

In [139]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

        date  product_id  ...  date_day  date_dow
0 2019-12-10        5628  ...        10         1
1 2018-08-15        3646  ...        15         2
2 2018-10-23        1859  ...        23         1
3 2019-08-17        7292  ...        17         5
4 2019-01-06        4344  ...         6         6

[5 rows x 9 columns]

In [140]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  ... date_day  date_dow  date_dow_name
0 2019-12-10       2019          12  ...       10         1        Tuesday
1 2018-08-15       2018           8  ...       15         2      Wednesday
2 2018-10-23       2018          10  ...       23         1        Tuesday
3 2019-08-17       2019           8  ...       17         5       Saturday
4 2019-01-06       2019           1  ...        6         6         Sunday

[5 rows x 7 columns]

In [141]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  ... date_dow  date_dow_name  date_is_weekend
0 2019-12-10       2019          12  ...        1        Tuesday                0
1 2018-08-15       2018           8  ...        2      Wednesday                0
2 2018-10-23       2018          10  ...        1        Tuesday                0
3 2019-08-17       2019           8  ...        5       Saturday                1
4 2019-01-06       2019           1  ...        6         Sunday                1

[5 rows x 8 columns]

In [145]:
# Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week

In [146]:
date.sample(4)

          date  product_id  city_id  ...  date_dow_name  date_is_weekend  date_week
548 2019-11-03        5917        2  ...         Sunday                1         44
958 2019-11-04        1875       13  ...         Monday                0         45
436 2019-10-11         983       25  ...         Friday                0         41
405 2019-07-26        4207        0  ...         Friday                0         30

[4 rows x 12 columns]

In [147]:
# Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  ... date_is_weekend  date_week  quarter
0 2019-12-10       2019          12  ...               0         50        4
1 2018-08-15       2018           8  ...               0         33        3
2 2018-10-23       2018          10  ...               0         43        4
3 2019-08-17       2019           8  ...               1         33        3
4 2019-01-06       2019           1  ...               1          1        1

[5 rows x 10 columns]

In [ ]:
# Extract Semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

In [150]:
# If quarter is 1, 2, or 3 → semester = 1
# If quarter is 4 → semester = 2
date['semester']=np.where(date['quarter'].isin([1,2,3]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month  ... date_week  quarter  semester
0 2019-12-10       2019          12  ...        50        4         2
1 2018-08-15       2018           8  ...        33        3         1
2 2018-10-23       2018          10  ...        43        4         2
3 2019-08-17       2019           8  ...        33        3         1
4 2019-01-06       2019           1  ...         1        1         1

[5 rows x 11 columns]

In [152]:
# gets the current date and time of your system
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 4, 13, 5, 41, 19, 244742)

In [153]:
today - date['date']

0     2316 days 05:41:19.244742
1     2798 days 05:41:19.244742
2     2729 days 05:41:19.244742
3     2431 days 05:41:19.244742
4     2654 days 05:41:19.244742
                 ...
995   2744 days 05:41:19.244742
996   2685 days 05:41:19.244742
997   2533 days 05:41:19.244742
998   2598 days 05:41:19.244742
999   2372 days 05:41:19.244742
Name: date, Length: 1000, dtype: timedelta64[ns]

In [157]:
(today - date['date']).dt.days

0      2316
1      2798
2      2729
3      2431
4      2654
       ...
995    2744
996    2685
997    2533
998    2598
999    2372
Name: date, Length: 1000, dtype: int64

In [165]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
).clip(lower=0)

## Working with Time

In [166]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [168]:
time['date']=pd.to_datetime(time['date'])

In [169]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [170]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

                 date  ... sec
0 2013-12-15 00:50:00  ...   0
1 2014-04-29 23:40:00  ...   0
2 2012-12-30 00:21:00  ...   0
3 2014-11-28 00:31:00  ...   0
4 2013-10-26 23:11:00  ...   0

[5 rows x 5 columns]

In [171]:
# Extract Time part
time['time'] = time['date'].dt.time

time.head()

                 date  ...      time
0 2013-12-15 00:50:00  ...  00:50:00
1 2014-04-29 23:40:00  ...  23:40:00
2 2012-12-30 00:21:00  ...  00:21:00
3 2014-11-28 00:31:00  ...  00:31:00
4 2013-10-26 23:11:00  ...  23:11:00

[5 rows x 6 columns]

In [172]:
# Time difference
today - time['date']

0     4502 days 04:51:19.244742
1     4366 days 06:01:19.244742
2     4852 days 05:20:19.244742
3     4154 days 05:10:19.244742
4     4551 days 06:30:19.244742
                 ...
995   5141 days 04:51:19.244742
996   4462 days 06:27:19.244742
997   4927 days 06:04:19.244742
998   5043 days 06:07:19.244742
999   4315 days 06:16:19.244742
Name: date, Length: 1000, dtype: timedelta64[ns]

In [173]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.889903e+08
1      3.772441e+08
2      4.192320e+08
3      3.589242e+08
4      3.932298e+08
           ...
995    4.441999e+08
996    3.855400e+08
997    4.257147e+08
998    4.357372e+08
999    3.728386e+08
Name: date, Length: 1000, dtype: float64

In [174]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.483171e+06
1      6.287401e+06
2      6.987200e+06
3      5.982070e+06
4      6.553830e+06
           ...
995    7.403331e+06
996    6.425667e+06
997    7.095244e+06
998    7.262287e+06
999    6.213976e+06
Name: date, Length: 1000, dtype: float64

In [175]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108052.855346
1      104790.022012
2      116453.338679
3       99701.172012
4      109230.505346
           ...
995    123388.855346
996    107094.455346
997    118254.072012
998    121038.122012
999    103566.272012
Name: date, Length: 1000, dtype: float64