In [37]:
import pandas as pd

In [38]:
df=pd.read_csv('/content/customer.csv')

In [39]:
df.sample(5)

    age  gender   review education purchased
21   32    Male  Average        PG        No
38   45  Female     Good    School        No
43   27    Male     Poor        PG        No
25   57  Female     Good    School        No
12   51    Male     Poor    School        No

In [40]:
df=df.iloc[:,2:]

In [41]:
df.sample(4)

     review education purchased
48     Good        UG       Yes
27     Poor        PG        No
37  Average        PG       Yes
12     Poor    School        No

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [44]:
X_train

     review education
47     Good        PG
28     Poor    School
0   Average    School
36     Good        UG
19     Poor        PG
35     Poor    School
32  Average        UG
33     Good        PG
27     Poor        PG
15     Poor        UG
21  Average        PG
8   Average        UG
4   Average        UG
2      Good        PG
24  Average        PG
10     Good        UG
38     Good    School
44  Average        UG
31     Poor    School
26     Poor        PG
22     Poor        PG
9      Good        UG
18     Good    School
29  Average        UG
17     Poor        UG
41     Good        PG
49     Good        UG
13  Average    School
39     Poor        PG
48     Good        UG
25     Good    School
6      Good    School
7      Poor    School
1      Poor        UG
12     Poor    School
20  Average    School
14     Poor        PG
42     Good        PG
37  Average        PG
30  Average        UG

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School', 'UG', 'PG']])

In [47]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [48]:
X_train=oe.transform(X_train)

In [49]:
X_train

array([[2., 2.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 1.]])

In [50]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [51]:
X_train

array([[2., 2.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [1., 1.]])

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le=LabelEncoder()

In [54]:
le.fit(y_train)

LabelEncoder()

In [55]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [56]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [57]:
y_train

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0])