In [12]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [13]:
df=sns.load_dataset('titanic')
df = df[['age','pclass','sibsp','parch','survived']]
df.head()

    age  pclass  sibsp  parch  survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [14]:
df.shape

(891, 5)

In [15]:
df.dropna(inplace=True)

In [16]:
df.head()

    age  pclass  sibsp  parch  survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [17]:
df.shape

(714, 5)

In [18]:
X=df.iloc[:, 0:4]
y=df.iloc[:,-1]

In [19]:
X.head()

    age  pclass  sibsp  parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [20]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

### Applying Feature Construction

In [21]:
X['Family_size']=X['sibsp']+X['parch'] + 1

In [22]:
X.head()

    age  pclass  sibsp  parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [23]:
def fam_type(num):
  if num==1:
    return 0
  elif num > 1 and num<=4:
    return 1
  else:
    return 2

In [25]:
fam_type(5)

2

In [26]:
X['Family_type']=X['Family_size'].apply(fam_type)

In [27]:
X.head(3)

    age  pclass  sibsp  parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0

In [28]:
X.drop(columns=['sibsp','parch','Family_size'], inplace=True)

In [29]:
X.head()

    age  pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [30]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

### Feature Splitting

In [33]:
df = pd.read_csv('train.csv')

In [34]:
df.head(2)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [35]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [41]:

df['Title'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]

In [42]:
df[['Title', 'Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [51]:
np.round(df.groupby('Title')['Survived'].mean().sort_values(ascending=True),3)

Title
Capt            0.000
Don             0.000
Jonkheer        0.000
Rev             0.000
Mr              0.157
Dr              0.429
Col             0.500
Major           0.500
Master          0.575
Miss            0.698
Mrs             0.792
Lady            1.000
Mme             1.000
Mlle            1.000
Ms              1.000
Sir             1.000
the Countess    1.000
Name: Survived, dtype: float64

In [52]:
df['IS_Married']=0
df['IS_Married'].loc[df['Title']=='Mrs']=1

/tmp/ipykernel_7986/4023083785.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['IS_Married'].loc[df['Title']=='Mrs']=1
/tmp/ipykernel_7986/4023083785.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IS_Married'].loc[df['Title']=='Mrs']=1

In [53]:
df['IS_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: IS_Married, Length: 891, dtype: int64